export enum BodyArea {
  // Cabeça e Pescoço
  ROSTO = 'ROSTO',
  PESCOCO = 'PESCOCO',
  NUCA = 'NUCA',
  
  // Tronco - Frente
  PEITO = 'PEITO',
  PEITO_SUPERIOR = 'PEITO_SUPERIOR',
  PEITO_LATERAL = 'PEITO_LATERAL',
  COSTELAS = 'COSTELAS',
  BARRIGA = 'BARRIGA',
  ABDOMEN = 'ABDOMEN',
  
  // Tronco - Trás
  COSTAS = 'COSTAS',
  COSTAS_SUPERIOR = 'COSTAS_SUPERIOR',
  COSTAS_COMPLETAS = 'COSTAS_COMPLETAS',
  LOMBAR = 'LOMBAR',
  
  // Braços
  BRACO = 'BRACO',
  BRACO_COMPLETO = 'BRACO_COMPLETO',
  BRACO_SUPERIOR = 'BRACO_SUPERIOR',
  BRACO_INTERNO = 'BRACO_INTERNO',
  BRACO_EXTERNO = 'BRACO_EXTERNO',
  ANTEBRACO = 'ANTEBRACO',
  ANTEBRACO_COMPLETO = 'ANTEBRACO_COMPLETO',
  ANTEBRACO_INTERNO = 'ANTEBRACO_INTERNO',
  ANTEBRACO_EXTERNO = 'ANTEBRACO_EXTERNO',
  COTOVELO = 'COTOVELO',
  
  // Mãos
  MAO = 'MAO',
  MAO_COMPLETA = 'MAO_COMPLETA',
  DEDOS = 'DEDOS',
  PULSO = 'PULSO',
  
  // Ombros
  OMBRO = 'OMBRO',
  OMBRO_COMPLETO = 'OMBRO_COMPLETO',
  
  // Pernas
  PERNA_COMPLETA = 'PERNA_COMPLETA',
  COXA = 'COXA',
  COXA_INTERNA = 'COXA_INTERNA',
  COXA_EXTERNA = 'COXA_EXTERNA',
  JOELHO = 'JOELHO',
  PANTURRILHA = 'PANTURRILHA',
  CANELA = 'CANELA',
  
  // Pés
  PE = 'PE',
  PE_COMPLETO = 'PE_COMPLETO',
  TORNOZELO = 'TORNOZELO',
  DEDOS_PE = 'DEDOS_PE'
}
